config/routes.rb
Rails.application.routes.draw do
  root to: "messages#new"
  post "/messages", to: "messages#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    flash[:notice] = params[:notice]
  end
 
  def create
    # account_sid = 'AC534b4e3bfd7c248027f6721be7abf902'
    # auth_token = '4b1c491ff9e1bf678e654b4be6abd8fc'
    # client = Twilio::REST::Client.new(account_sid, auth_token)

    # from = '+12055283142' # Your Twilio number

    # client.messages.create(
    # from: from,
    # to: params[:number],
    # body: params[:message]
    # )
    # byebug
    sms = SendSMS.new(params[:message], params[:number])
    sms.call

    redirect_to(action: :new, notice: 'SMS enviado o/')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMessenger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/home.html.erb
<h1>Messages#home</h1>
<p>Find me in app/views/messages/home.html.erb</p>

app/views/messages/new.html.erb
<h3>Envie seu SMS</h3>
​
<hr>
​
<%= form_tag messages_path do %>
  Mensagem: <%= text_area_tag :message %><br><br>
  Número: <%= text_field_tag :number %><br><br>
  <%= submit_tag 'Enviar SMS' %>
<% end %>
​
<hr>
​
<% if flash[:notice] %>
  <div><%= flash[:notice] %></div>
<% end %>